title: Traveling the World with the Kids!
description: Join the **CharMing** family on our journeys as we explore different countries, cultures, and awesome food!
baseurl: ""
url: "https://travelwithkids.github.io" # Replace with your GitHub username
theme: jekyll-theme-minimal
markdown: kramdown
author: CharMing

# Social Links
# social_links:
  #twitter: "https://twitter.com/yourhandle" # Replace with your Twitter handle
  #instagram: "https://instagram.com/yourhandle" # Replace with your Instagram handle
  #facebook: "https://facebook.com/yourhandle" # Replace with your Facebook handle
