title: Traveling the World with the Kids
description: Join me on my journeys as I explore different countries, cultures, and adventures!
baseurl: ""
url: "https://travelwithkids.github.io" # Replace with your GitHub username
theme: jekyll-theme-minimal
markdown: kramdown
author: Your Name

# Social Links
social_links:
  twitter: "https://twitter.com/yourhandle" # Replace with your Twitter handle
  instagram: "https://instagram.com/yourhandle" # Replace with your Instagram handle
  facebook: "https://facebook.com/yourhandle" # Replace with your Facebook handle
